name: easy_stock_app
description: A new Flutter project for stock management.
publish_to: 'none' 

version: 5.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  # google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  # flutter_screenutil: ^5.9.0
  # flutter_barcode_scanner: ^2.0.0
  flutter_secure_storage: ^9.2.2
  flutter_secure_token_manager: ^0.0.1
  http: ^1.2.0
  flutter_typeahead: ^4.0.0
  path: ^1.9.0
  intl: ^0.19.0
  another_flushbar: ^1.12.30
  package_info_plus: ^5.0.1
  share_plus: ^7.2.2
  pdf: ^3.11.3
  # pdf: ^3.11.1
  pdfx: ^2.6.0
  path_parsing: ^1.1.0
  path_provider: ^2.1.5
  number_to_words: ^1.0.0
  multi_select_flutter: ^4.1.3
  numberpicker: ^2.1.2
  flutter_circular_progress_indicator: ^0.0.3
  shimmer: ^3.0.0
  # printing: ^5.9.0
  google_fonts: ^6.2.1
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1
  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  flutter_pdfview: ^1.4.0
 
  
  # htmltopdfwidgets: ^1.0.9
  # blue_thermal_printer: ^1.2.0
  # esc_pos_utils: ^1.0.0
  # syncfusion_flutter_pdfviewer: ^24.1.41

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets to your application.
  assets:
  - assets/images/
  - assets/icons/
  # - assets/fonts/Roboto-Regular.ttf
  # - assets/fonts/Roboto-Bold.ttf

  # Define custom fonts here.
  # flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          # weight: 700

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
